version: "3.7"
services:
  apache:
    labels:
      type: httpd
    image: httpd:2.4-alpine
    deploy:
      replicas: 1
    configs:
      - source: httpd-conf
        target: /usr/local/apache2/conf/httpd.conf
    environment:
      DOCUMENTROOT: /var/www/html/${DOCUMENTROOT}
      PHPSERVER: phpserver
    volumes:
      - type: bind
        source: ${HOST_PROJECT_DIR}
        target: /var/www/html
        read_only: true
    ports:
      - '${HOST_PORT}:80'
    networks:
      - phpfpmnetwork
  phpserver:
    labels:
      type: php
    image: besogon1/php-fpm-dbs
    deploy:
      replicas: 1
    configs:
      - source: php-ini
        target: /usr/local/etc/php/php.ini
      - source: php-fpm
        target: /usr/local/etc/php-fpm.conf
    ports:
      - '${XDEBUG_PORT}:9001'
    volumes:
      - type: bind
        source: ${HOST_PROJECT_DIR}
        target: /var/www/html
    environment:
      XDEBUG_CONFIG: $XDEBUG_CONFIG
      XDEBUG_SESSION: $XDEBUG_SESSION
    networks:
      phpfpmnetwork:
  memcached:
    image: memcached:1.6.5-alpine
    deploy:
      replicas: 1
    networks:
      - phpfpmnetwork
  database:
    labels:
      type: database
    image: postgres:13-alpine
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    configs:
      - source: postgres-conf
        target: /usr/local/share/postgresql/postgres.conf
    secrets:
      - postgres-passwd
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      phpfpmnetwork:
        aliases:
          - database

networks:
  phpfpmnetwork:

configs:
  httpd-conf:
    file: ${APACHE_CONF}
  php-ini:
    file: ${PHP_INI}
  php-fpm:
    file: ${PHP_FPM}
  postgres-conf:
    file: ${MY_DB_CONF}

secrets:
  postgres-passwd:
    file: ${MY_PWD}
volumes:
  postgres_data:
    external: true
    name: phpapachepostgres_mysql